# name-template: 'v$RESOLVED_VERSION'
# tag-template: 'v$RESOLVED_VERSION'
# autolabeler:
#   - label: 'chore'
#     files:
#       - '*.md'
#     branch:
#       - '/docs{0,1}\/.+/'
#   - label: 'bug'
#     branch:
#       - '/fix\/.+/'
#     title:
#       - '/fix/i'
#   - label: 'enhancement'
#     branch:
#       - '/feature\/.+/'
#     body:
#       - '/JIRA-[0-9]{1,4}/'
# categories:
#   - title: '🚀 Features'
#     labels:
#       - 'feature'
#       - 'feat'
#       - 'enhancement'
#   - title: '🐛 Bug Fixes'
#     labels:
#       - 'fix'
#       - 'bugfix'
#       - 'bug'
#   - title: '🧰 Maintenance'
#     labels:
#       - 'fix'
#       - 'bugfix'
#       - 'bug'
#       - 'chore'
# change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
# template: |
#   ## What's Changed

#   $CHANGES

